const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Physics,
		C3.Plugins.List,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{ids: 0},
	{collCheck1: 0},
	{collCheck2: 0},
	{collCheck3: 0},
	{collCheck4: 0},
	{collCheck5: 0},
	{collider: 0},
	{creator1: 0},
	{creator2: 0},
	{creator3: 0},
	{creator4: 0},
	{targets: 0},
	{target: 0},
	{lock1: 0},
	{lock2: 0},
	{lock3: 0},
	{Pin: 0},
	{lockTxt: 0},
	{point1a: 0},
	{point1b: 0},
	{point2a: 0},
	{point2b: 0},
	{point3a: 0},
	{point3b: 0},
	{coll: 0},
	{Pops1: 0},
	{Pops2: 0},
	{Pops3: 0},
	{Pops4: 0},
	{Pops5: 0},
	{rope1: 0},
	{rope2: 0},
	{rope3: 0},
	{MoveTo: 0},
	{scroll_1: 0},
	{scroll_2: 0},
	{scroll_3: 0},
	{sfLock1: 0},
	{sfLock2: 0},
	{sfLock3: 0},
	{Bird1: 0},
	{Bird2: 0},
	{Bird3: 0},
	{Bird4: 0},
	{Bird5: 0},
	{Physics: 0},
	{blockWood: 0},
	{Eggs: 0},
	{chick: 0},
	{eggnest: 0},
	{blockIce: 0},
	{blocked: 0},
	{blockWood3: 0},
	{blockHex: 0},
	{boostColl: 0},
	{BoostLine: 0},
	{bush: 0},
	{chainPop: 0},
	{popsCount: 0},
	{List: 0},
	{rot: 0},
	{rots: 0},
	{rotjoint: 0},
	{shapes: 0},
	{txtr1: 0},
	{walls: 0},
	{obstcls: 0},
	{zgrass: 0},
	{Audio: 0},
	{Touch: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Fade: 0},
	{prtclCollDestr: 0},
	{prtclPrtcl: 0},
	{vispops: 0},
	{prtclBush: 0},
	{prtclPrtcl2: 0},
	{prtclHexDestr: 0},
	{prtclGrass: 0},
	{prtclHex: 0},
	{bg: 0},
	{txtFps: 0},
	{zscreen: 0},
	{zbg: 0},
	{txtFps2: 0},
	{guiTopPanel: 0},
	{btns: 0},
	{guiWLpanel: 0},
	{btnsPause: 0},
	{sfLvlNum: 0},
	{btnTrgtStart: 0},
	{moves: 0},
	{sfMoves: 0},
	{sfTarg1: 0},
	{sfTarg2: 0},
	{sfTarg3: 0},
	{zbgtargets: 0},
	{target1: 0},
	{target2: 0},
	{target3: 0},
	{sfLvls: 0},
	{btnsMenu: 0},
	{lvl: 0},
	{btnLvls: 0},
	{GameName: 0},
	{famPhysics: 0},
	{famPOPs: 0},
	{famPoints: 0},
	{famRope1: 0},
	{famRope2: 0},
	{famRope3: 0},
	{Bullet: 0},
	{famLOCKs: 0},
	{famCOLLs: 0},
	{famBirds: 0},
	{famTargets: 0},
	{famVisPops: 0},
	{famEggs: 0},
	{waitlose: 0},
	{sfx: 0},
	{game: 0},
	{poptouched: 0},
	{destroyed: 0},
	{sfxLock: 0},
	{previousLink: 0},
	{a: 0},
	{Parameter0: 0},
	{level: 0}
];

self.InstanceType = {
	collCheck1: class extends self.ISpriteInstance {},
	collCheck2: class extends self.ISpriteInstance {},
	collCheck3: class extends self.ISpriteInstance {},
	collCheck4: class extends self.ISpriteInstance {},
	collCheck5: class extends self.ISpriteInstance {},
	collider: class extends self.ISpriteInstance {},
	creator1: class extends self.ISpriteInstance {},
	creator2: class extends self.ISpriteInstance {},
	creator3: class extends self.ISpriteInstance {},
	creator4: class extends self.ISpriteInstance {},
	lock1: class extends self.ISpriteInstance {},
	lock2: class extends self.ISpriteInstance {},
	lock3: class extends self.ISpriteInstance {},
	lockTxt: class extends self.ITextInstance {},
	point1a: class extends self.ISpriteInstance {},
	point1b: class extends self.ISpriteInstance {},
	point2a: class extends self.ISpriteInstance {},
	point2b: class extends self.ISpriteInstance {},
	point3a: class extends self.ISpriteInstance {},
	point3b: class extends self.ISpriteInstance {},
	Pops1: class extends self.ISpriteInstance {},
	Pops2: class extends self.ISpriteInstance {},
	Pops3: class extends self.ISpriteInstance {},
	Pops4: class extends self.ISpriteInstance {},
	Pops5: class extends self.ISpriteInstance {},
	rope1: class extends self.ISpriteInstance {},
	rope2: class extends self.ISpriteInstance {},
	rope3: class extends self.ISpriteInstance {},
	scroll_1: class extends self.ISpriteInstance {},
	scroll_2: class extends self.ISpriteInstance {},
	scroll_3: class extends self.ISpriteInstance {},
	sfLock1: class extends self.ISpriteFontInstance {},
	sfLock2: class extends self.ISpriteFontInstance {},
	sfLock3: class extends self.ISpriteFontInstance {},
	Bird1: class extends self.ISpriteInstance {},
	Bird2: class extends self.ISpriteInstance {},
	Bird3: class extends self.ISpriteInstance {},
	Bird4: class extends self.ISpriteInstance {},
	Bird5: class extends self.ISpriteInstance {},
	blockWood: class extends self.ISpriteInstance {},
	Eggs: class extends self.ISpriteInstance {},
	eggnest: class extends self.ISpriteInstance {},
	blockIce: class extends self.ISpriteInstance {},
	blockWood3: class extends self.ISpriteInstance {},
	chick: class extends self.ISpriteInstance {},
	blockHex: class extends self.ISpriteInstance {},
	boostColl: class extends self.ISpriteInstance {},
	BoostLine: class extends self.ISpriteInstance {},
	bush: class extends self.ISpriteInstance {},
	chainPop: class extends self.ISpriteInstance {},
	List: class extends self.IListInstance {},
	rots: class extends self.ISpriteInstance {},
	rotjoint: class extends self.ISpriteInstance {},
	shapes: class extends self.ISpriteInstance {},
	txtr1: class extends self.ITiledBackgroundInstance {},
	walls: class extends self.ITiledBackgroundInstance {},
	obstcls: class extends self.ISpriteInstance {},
	zgrass: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	prtclCollDestr: class extends self.ISpriteInstance {},
	prtclPrtcl: class extends self.IParticlesInstance {},
	vispops: class extends self.ISpriteInstance {},
	prtclBush: class extends self.IParticlesInstance {},
	prtclPrtcl2: class extends self.IParticlesInstance {},
	prtclHexDestr: class extends self.ISpriteInstance {},
	prtclGrass: class extends self.IParticlesInstance {},
	prtclHex: class extends self.IParticlesInstance {},
	bg: class extends self.ISpriteInstance {},
	txtFps: class extends self.ITextInstance {},
	zscreen: class extends self.ITiledBackgroundInstance {},
	zbg: class extends self.ITiledBackgroundInstance {},
	txtFps2: class extends self.ITextInstance {},
	guiTopPanel: class extends self.IWorldInstance {},
	btns: class extends self.ISpriteInstance {},
	guiWLpanel: class extends self.ISpriteInstance {},
	btnsPause: class extends self.ISpriteInstance {},
	sfLvlNum: class extends self.ISpriteFontInstance {},
	btnTrgtStart: class extends self.ISpriteInstance {},
	sfMoves: class extends self.ISpriteFontInstance {},
	sfTarg1: class extends self.ISpriteFontInstance {},
	sfTarg2: class extends self.ISpriteFontInstance {},
	sfTarg3: class extends self.ISpriteFontInstance {},
	zbgtargets: class extends self.ITiledBackgroundInstance {},
	target1: class extends self.ISpriteInstance {},
	target2: class extends self.ISpriteInstance {},
	target3: class extends self.ISpriteInstance {},
	sfLvls: class extends self.ISpriteFontInstance {},
	btnsMenu: class extends self.ISpriteInstance {},
	btnLvls: class extends self.ISpriteInstance {},
	GameName: class extends self.ISpriteInstance {},
	famPhysics: class extends self.ISpriteInstance {},
	famPOPs: class extends self.ISpriteInstance {},
	famPoints: class extends self.ISpriteInstance {},
	famRope1: class extends self.ISpriteInstance {},
	famRope2: class extends self.ISpriteInstance {},
	famRope3: class extends self.ISpriteInstance {},
	famLOCKs: class extends self.ISpriteInstance {},
	famCOLLs: class extends self.ISpriteInstance {},
	famBirds: class extends self.ISpriteInstance {},
	famTargets: class extends self.ISpriteInstance {},
	famVisPops: class extends self.ISpriteInstance {},
	famEggs: class extends self.ISpriteInstance {},
	waitlose: class extends self.ISpriteInstance {}
}